print('请输入第一只猫的名字：')
cat1 = input()
print('请输入第二只猫的名字：')
cat2 = input()
print('请输入第三只猫的名字：')
cat3 = input()
print('请输入第四只猫的名字：')
cat4 = input()
print('请输入第五只猫的名字：')
cat5 = input()
print('请输入第六只猫的名字：')
cat6 = input()

print('这六只猫是：')
print(cat1 +' '+ cat2 +' '+ cat3 +' '+ cat4 +' '+ cat5 +' '+ cat6 )